export enum CloudNativeResources {
    aKSDeploymentBulletPointFour = "Example application deployed for testing",
    aKSDeploymentBulletPointOne = "A scalable AKS cluster with a NGINX Ingress Controller",
    aKSDeploymentBulletPointThree = "SSL certificate applied to the public endpoint",
    aKSDeploymentBulletPointTwo = "Public endpoint using a pre-owned custom domain secured via a Let's Encrypt certificate.",
    aksDeploymentDescription = "This workload contains:",
    ariaLabelCloudShellContainer = "Executable Docs terminal",
    azureContainerAppsDocumentation = "Azure Container Apps Documentation",
    azureContainerRegistry = "Create an Azure Container Registry",
    azureKubernetes = "Azure Kubernetes Service Documentation",
    basics = "Basics",
    cesQuestion = "How easy or difficult was it to use this page?",
    clickHere = "Navigate to the resource group.",
    cloudshellNoSubscriptionId = "We couldn't retrieve a subscription ID to provision Cloud Shell. You may not have an active subscription. Please create one and try the deployment again.",
    configIntroMessage = "Select the subscription and region for the workload. If no subscriptions are available for deployment, sign up for a free trial.",
    confirm = "Confirm",
    connectingTerminal = "Connecting terminal...",
    createCloudNativePythonContainer = "Create Cloud Native Python Container",
    createCloudNativePythonContainerDetailsBulletPoint1 = "An optimally sized Linux VM for small scale LEMP workloads",
    createCloudNativePythonContainerDetailsBulletPoint2 = "Fully configured LEMP stack",
    createCloudNativePythonContainerDetailsBulletPoint3 = "SFTP access for file upload",
    createCloudNativePythonContainerDetailsBulletPoint4 = "Utilizes port 22 for on-machine work",
    createCloudNativePythonContainerDetailsDescription = "A great starter for a single VM LEMP stack. Ideal for prototyping or development.",
    createContainerAppDeploymentFromSource = "Create a Container App leveraging Blob Store, SQL, and Computer Vision",
    createLinuxVMAndSSHNextStepFour = "Load Balance VMs",
    createLinuxVMAndSSHNextStepThree = "Create Custom VM Images",
    createLinuxVMAndSSHNextStepTwo = "Use Cloud-Init to Initialize a Linux VM on First Boot",
    createLinuxVMSecureWebServerNextStepFour = "Create VM Scale Set",
    createLinuxVMSecureWebServerNextStepTwo = "Create VM Scale Set",
    createLinuxVMSSwithAppGW = "Create a Virtual Machine Scale Set with Application Gateway with Linux image",
    createRHELVMAndSSH = "Create a Red Hat Enterprise Linux virtual machine with the Azure CLI on Azure",
    createStaticWebApp = "Azure Static Web Apps Quickstart: Building Your First Static Site Using the Azure CLI",
    createWordPressDeployment = "Quickstart: Deploy a Scalable and Secure WordPress instance on AKS",
    customResource = "Custom resource",
    cvaQuestion = "How valuable is this page in meeting your needs?",
    dataCollectionRule = "Data Collection Rule",
    deploy = "Deploy",
    deployIgonAksNxtStpOne = "Real-world scenarios where Inspektor Gadget can help you",
    deployIgonAksNxtStpThree = "Run your own eBPF program",
    deployIgonAksNxtStpTwo = "Explore the available gadgets",
    deployIgonAksTitle = "Deploy Inspektor Gadget in an AKS cluster",
    deploymentError = "Deployment Error",
    deploymentFailed = "Your deployment failed",
    deploymentSummary = "Deployment summary",
    deploymentSummaryDescription = "Most configurations can be changed after the deployment.",
    deploymentSummaryTitle = "Deployment Summary",
    disk = "Disk",
    docNotSupported = "The Executable Doc you are attempting to run is not currently supported.",
    doNotLeave = "Do not leave or refresh page until the process is complete.",
    downloadSourceFiles = "Download source file",
    failed = "Failed.",
    failGetUserSettings = "Unable to retrieve Cloudshell settings for user. Cloudshell session terminated.",
    failurePaneResourceGroup = "You deployed the new resource group {0}. To prevent charges, we recommend deleting the resource group.",
    freeTrial = "Free Trial",
    getSourceFiles = "Get the source files",
    guidedDeploy = "Guided deployment",
    healthProbe = "Health Probes in Azure Container Apps",
    improperReconnectMessageWithoutResourceGroup = "Your deployment was interrupted and cancelled. Please restart the workload deployment by going back to the home page.",
    improperReconnectMessageWithResourceGroup = "Your deployment was interrupted and cancelled. A resource group may have been automatically created. Please delete the resource group to avoid future charges. Restart the workload deployment by going back to the home page.",
    improperReconnectTitle = "Your deployment was interrupted",
    initializing = "Initializing",
    initializingLoading = "Initializing...",
    lAMPLinuxVM = "Create a LEMP stack on a Linux VM",
    lAMPLinuxVMDescription = "Deploy a NGINX web server, MySQL, and PHP (the LEMP stack) on an Ubuntu VM.",
    learnMode = "Guided deployment",
    learnModeIntro = "Deploy Azure services using Azure CLI. Azure will create a resource group for you that you can change later. This is a step by step learning experience. The terminal is non-interactive until the deployment is complete.",
    learnMore = "Learn more",
    leavingAlert = "Leaving the page will stop the deployment. You will not be able to navigate back to this page.",
    linuxVMCustomDomain = "Create an AKS cluster with a custom domain and HTTPS",
    linuxVMCustomDomainDescription = "Create an AKS cluster with a NGINX Ingress Controller and custom domain secured via a Let's Encrypt certificate.",
    linuxVMSecureWebServer = "Create a Linux VM with a secure web server",
    linuxVMSecureWebServerDescription = "Deploy a NGINX web server secured via HTTPS on a D-Series virtual machine.",
    linuxVMSecureWebServerDetailsBulletPoint1 = "An Ubuntu 2204 Linux VM (Standard DS2 v2)",
    linuxVMSecureWebServerDetailsBulletPoint2 = "SSL certificate autorotation hosted in Azure Key Vault",
    linuxVMSecureWebServerDetailsBulletPoint3 = "Built in monitoring and reporting",
    linuxVMSecureWebServerDetailsBulletPoint4 = "Built in monitoring and reporting",
    linuxVMSecureWebServerDetailsDescription = "This is a single VM with a pre-configured NGINX web server.",
    linuxVMSSH = "Create a Linux VM and SSH",
    linuxVMSSHDescription = "Install the latest Ubuntu image, generate a private key, and connect to it using SSH.",
    linuxVMSSHDetailsBulletPoint1 = "An Ubuntu 2204 Linux VM (Standard DS1 v2)",
    linuxVMSSHDetailsBulletPoint2 = "30 GB Premium SSD (120 IOPS, 25 MBps)",
    linuxVMSSHDetailsBulletPoint3 = "Network interface with public IP and network security group",
    linuxVMSSHDetailsBulletPoint4 = "Port 22 will be opened",
    linuxVMSSHDetailsDescription = "A relatively modest Linux VM (Ubuntu 2204) ideal for exploring Linux on Azure and/or running lightweight jobs.",
    loadBalanceVMs = "Load Balance VMs",
    location = "Location",
    managedCluster = "Managed Cluster",
    manageSecrets = "Manage Secrets in Container App",
    name = "Name",
    networkError = "We failed to find your active Azure subscriptions. Please refresh the page or try again later.",
    networkInterface = "Network interface",
    networkSecurityGroup = "Network security group",
    nextSteps = "Next Steps",
    noActiveSubscription = "No active susbscription found. Please sign up for",
    noSubscriptionApplied = "No subscription applied",
    noSubscriptionsError = "You do not currently have any active Azure subscription. To continue, create an Azure subscription.",
    noValidSubscriptions = "You do not have deployment access for any given subscriptions. Please contact your administrator to request access or sign up for a free trial",
    pendingDeploymentError = "We detected you have a pending deployment. Please wait till the previous deployment is finished to start a new one.",
    pricingMessage = "Deploying resources will incur charges. To prevent charges, we recommend deleting resources when they are no longer needed.",
    privateDNSZones = "Private DNS Zones",
    publicIpAddr = "Public IP address",
    quickDeploy = "Quick deployment",
    readDocumentation = "Read documentation",
    redeployRefresh = "Click here to re-deploy",
    region = "Region",
    requestCloudshell = "Requesting a Cloud Shell.",
    resourceGroup = "Resource Group",
    resourcesAccordionTitlePlural = "View all {0} resources deployed",
    resourcesAccordionTitleSingular = "View all {0} resource deployed",
    resourcesDeployedCountPartTwo = "Visit the resource group to make any changes. Most configurations can be changed after the deployment.",
    resourcesDeployedCountPlural = "You deployed {0} resources within the new resource group",
    resourcesDeployedCountSingular = "You deployed {0} resource within the new resource group",
    resourceType = "Resource Type",
    run = "Run",
    runAllSteps = "Run all steps",
    runScript = "Quick deployment",
    scaleAKS = "Scale your Appplication in AKS",
    scalingAnAzureContainerApp = "Scaling an Azure Container App",
    search = "Search",
    sessionTerminated = "Cloudshell session terminated.",
    showLess = "Show less",
    showMore = "Show more",
    stepCount = "Step {0} of {1}",
    subscription = "Subscription",
    subscriptionSelectorAriaLabel = "Subscription dropdown",
    subscriptionSelectorHelptext = "Please choose a subscription with deployment access",
    subscriptionSelectorIntro = "Select your configurations in order to proceed with the deployment.",
    subscriptionSelectorPlaceholder = "No subscription applied",
    succeded = "Succeeded",
    successfulDeployment = "Your deployment was successful",
    terminalFailReconnect = "Unable to reconnect to Cloudshell terminal socket.",
    terminalFailReconnectDeployment = "Unable to reconnect to deployment.",
    terminalReconnect = "Terminal socket error detected. Attempting to reconnect.",
    tryAgain = "Try again",
    tryAgainSuggestion = "Click Try Again and select a sample scenario",
    tryRunning = "Try running the following command",
    tutorialsOverviewDescription = "Deploy Azure services using Azure CLI. Azure will create a resource group for you that you can change later. This is a default config that may or may not match your needs. Most configurations can be changed after the deployment.",
    tutorialsOverviewTitle = "Quick-start workloads using CLI",
    unableToAuthorizeCloudshell = "Unable to authorize Cloudshell session.",
    unableToConfigureEphemeral = "Unable to configure ephemeral Cloudshell settings. Cloudshell session terminated.",
    unableToConnectCloudshell = "Unable to connect to Cloudshell console. Cloudshell session terminated.",
    unableToProvisionEphemeral = "Unable to provision Cloudshell console. Cloudshell session terminated.",
    unableToValidateEphemeral = "Unable to validate ephemeral Cloud Shell settings. Reset User Settings (see: https://learn.microsoft.com/azure/cloud-shell/new-ui-shell-window#settings-menu). Cloud Shell session terminated.",
    untrustedOrigin = "Untrusted origin. Cloudshell session terminated.",
    updateAKS = "Update your application in AKS",
    viewAllSteps = "View all {0} steps",
    viewDetails = "View details",
    viewErrorDetails = "View error details",
    viewLess = "View less",
    virtualMachine = "Virtual machine",
    virtualnetwork = "Virtual network",
    visitResourceGroup = "Visit the resource group to make any changes.",
    vmDocumentation = "VM Documentation",
    searchForDocs = "Search for Executable Docs",
    // Constants for AzdDeploymentTerminal
    deployingResourceWarning = "Deploying resources will incur charges. To prevent excessive charges, we recommend deleting resources when they are no longer needed. ",
    learnMoreText = "Learn more",
    deployingResourceWarningLink = "https://go.microsoft.com/fwlink/?linkid=2312712",
    loginStep = "Step 1: Login",
    deployStep = "Step 2: Deploy",
    resourcesDeployedText = "Resources will be deployed",
    forMoreInformation = "For more information: ",
    readMe = "README on GitHub",
    successLoginText = "Successfully authenticated",
    deployResourcesExplanation = "Resource list",
    deploymentProgressText = "Deployment in progress",
    deploymentButtonText = "Deploy Template",
    loginButtonText = "Login",
    deployTemplateText = "Deploy template",
    viewDeploymentText = "View deployment",
    successfulDeploymentText = "Your deployment was successful",
    readmeOnGithubText = "README on GitHub",
    overviewTitle = "Overview",
    keyFeaturesTitle = "Key features",
    deploymentFailedText = "Deployment failed",
    deploymentFailedErrorText = "Your deployment has failed, feel free to delete  the resource group or attempt to deploy again.",
    retryDeploymentButtonText = "Retry deployment",
    deleteResourcesButtonText = "Delete resources",
    noTemplateInfoFoundId = "00000000-0000-0000-0000-000000000000",
    // Aria Label for AzdDeploymentTerminal
    ariaLabelDeploymentTerminal = "Deployment terminal",
    ariaLabelLoginButton = "Login button",
    ariaLabelDeployButton = "Deploy button",
    ariaLabelDeploymentLink = "Link to view deployment",
    ariaLabelErrorDeploymenLink = "Link to view deployment",
    ariaLabelReadMeLink = "Link for ReadMe on Github",
    ariaLabelPricingLink = "Link to learn more on Pricing",
    ariaLabelRetryButton = "Retry Deployment Button",
    ariaLabelDeleteResourcesButton = "Delete Resources Button",
    // ClassNames for AzdDeploymentTerminal
    classNameDeploymentTerminal = "deployment-terminal",
    classNameLoginButton = "login-button",
    classNameDeployButton = "deploy-button",
    classNameDeploymentLink = "deployment-link",
    classNameReadMeLink = "readme-link",
    classNamePricingLink = "pricing-link",

    // ========================================================================
    // METADATA.json
    // ========================================================================
    // Common Parameters
    resourceGroupParam = "Resource Group Name",
    aksClusterNameParam = "AKS Cluster Name",
    vmNameParam = "VM Name",

    // these are the strings for -> azure-docs/articles/aks/learn/quick-kubernetes-deploy-cli.md
    quickKubernetesTitle = "Deploy an Azure Kubernetes Service (AKS) cluster",
    quickKubernetesDescription = "Learn how to quickly deploy a Kubernetes cluster and deploy an application in Azure Kubernetes Service (AKS) using Azure CLI",
    quickKubernetesNextStepOne = "Prepare an application for AKS",
    quickKubernetesNextStepTwo = "AKS solution guidance",
    // these are the strings for -> azure-databases-docs/articles/mysql/flexible-server/tutorial-deploy-wordpress-on-aks.md
    flexibleServerTitle = "Tutorial: Deploy WordPress on AKS cluster by using Azure CLI",
    flexibleServerDescription = "Learn how to quickly build and deploy WordPress on AKS with Azure Database for MySQL - Flexible Server.",
    flexibleServerStackItemOne = "An Ubuntu 22.04 Linux VM (Standard DS2_v2)",
    flexibleServerStackItemTwo = "Azure Database for MySQL - Flexible Server: 8.0.21",
    flexibleServerStackItemThree = "NGINX web server",
    flexibleServerStackItemFour = "PHP version 8.1-fpm",
    flexibleServerStackItemFive = "Latest WordPress",
    flexibleServerStackItemSix = "Network interface with public IP and network security group",
    flexibleServerStackItemSeven = "Azure Private DNS Zone for Azure MySQL Flexible Server",
    flexibleServerStackItemEight = "Use port 22 for SSH and ports 80, 443 for web traffic",
    flexibleServerNextStepOne = "Access the Kubernetes web dashboard",
    flexibleServerNextStepTwo = "Scale your AKS cluster",
    flexibleServerNextStepThree = "Manage your Azure Database for MySQL flexible server instance",
    flexibleServerNextStepFour = "Configure server parameters for your database server",
    // these are the strings for -> azure-docs/articles/static-web-apps/get-started-cli.md
    staticWebAppTitle = "Deploy a Static site with the Azure Static Web Apps",
    staticWebAppDescription = "Learn to deploy a static site to Azure Static Web Apps with the Azure CLI.",
    staticWebAppNextStepOne = "Add an API via Azure functions to your static site",
    // these are the strings for -> azure-docs/articles/virtual-machine-scale-sets/flexible-virtual-machine-scale-sets-cli.md
    flexibleVMTitle = "Create virtual machines in a Flexible scale set using Azure CLI",
    flexibleVMDescription = "Learn how to create a Virtual Machine Scale Set in Flexible orchestration mode using Azure CLI.",
    flexibleVMNextStepOne = "Learn how to create a scale set in the Azure portal",
    flexibleVMNextStepTwo = "Learn about Virtual Machine Scale Sets",
    flexibleVMNextStepThree = "Automatically scale a Virtual Machine Scale Set with the Azure CLI",
    // these are the strings for -> azure-docs/articles/virtual-machines/linux/quick-create-cli.md
    quickCreateVMTitle = "Deploy a Linux virtual machine",
    quickCreateVMDescription = "In this quickstart, you learn how to use the Azure CLI to create a Linux virtual machine",
    quickCreateVMStackItemOne = "An Ubuntu 22.04 Linux VM (Standard DS1_v2)",
    quickCreateVMStackItemTwo = "30 GB Premium SSD (120 IOPS, 25 MBps)",
    quickCreateVMStackItemThree = "Network interface with public IP and network security group",
    quickCreateVMStackItemFour = "Port 22 will be opened",
    quickCreateVMNextStepOne = "Learn about virtual machines",
    quickCreateVMNextStepTwo = "Use Cloud-Init to initialize a Linux VM on first boot",
    quickCreateVMNextStepThree = "Create custom VM images",
    quickCreateVMNextStepFour = "Load Balance VMs",
    // these are the strings for -> azure-docs/articles/virtual-machines/linux/tutorial-lemp-stack.md
    lempStackTitle = "Tutorial - Deploy a LEMP stack using WordPress on a VM",
    lempStackDescription = "In this tutorial, you learn how to install the LEMP stack, and WordPress, on a Linux virtual machine in Azure.",
    lempStackNextStepOne = "Learn about virtual machines",
    lempStackNextStepTwo = "Create and manage Linux VMs with the Azure CLI",
    lempStackNextStepThree = "Secure your Linux VM",
    // these are the strings for -> DeployIGonAKS/README.md
    igonTitle = "Deploy Inspektor Gadget in an Azure Kubernetes Service cluster",
    igonDescription = "This tutorial shows how to deploy Inspektor Gadget in an AKS cluster",
    igonNextStepOne = "Real-world scenarios where Inspektor Gadget can help you",
    igonNextStepTwo = "Explore the available gadgets",
    igonNextStepThree = "Run your own eBPF program",
    // these are the strings for -> CreateAKSWebApp/README.md
    aksWebAppTitle = "Deploy a Scalable & Secure Azure Kubernetes Service cluster using the Azure CLI",
    aksWebAppDescription = "This tutorial where we will take you step by step in creating an Azure Kubernetes Web Application that is secured via https.",
    aksWebAppNextStepOne = "Azure Kubernetes Service Documentation",
    aksWebAppNextStepTwo = "Create an Azure Container Registry",
    aksWebAppNextStepThree = "Scale your Applciation in AKS",
    aksWebAppNextStepFour = "Update your application in AKS",
    // these are the strings for -> CreateRHELVMAndSSH/create-rhel-vm-ssh.md
    rhelVmTitle = "Quickstart: Use the Azure CLI to create a Red Hat Enterprise Linux Virtual Machine",
    rhelVmDescription = "In this quickstart, you learn how to use the Azure CLI to create a Red Hat Enterprise Linux virtual machine",
    rhelVmNextStepOne = "Learn about virtual machines",
    rhelVmNextStepTwo = "Create an Ubuntu Virtual Machine",
    rhelVmNextStepThree = "Create custom VM images",
    rhelVmNextStepFour = "Load Balance VMs",
    // these are the strings for -> AttachDataDiskLinuxVM/attach-data-disk-linux-vm.md
    attachDataDiskTitle = "Quickstart: Use the Azure CLI to create an Ubuntu Virtual Machine and attach an Azure Data Disk",
    attachDataDiskDescription = "In this quickstart, you learn how to use the Azure CLI to create an Ubuntu Linux virtual machine",
    attachDataDiskNextStepOne = "Learn about virtual machines",
    attachDataDiskNextStepTwo = "Use Cloud-Init to initialize a Linux VM on first boot",
    attachDataDiskNextStepThree = "Create custom VM images",
    attachDataDiskNextStepFour = "Load Balance VMs",
    // these are the strings for -> ObtainPerformanceMetricsLinuxSustem/obtain-performance-metrics-linux-system.md
    linuxSystemTitle = "Obtaining Performance metrics from a Linux system",
    linuxSystemDescription = "Learn how to obtainer Performance metrics from a Linux system.",
    // these are the strings for -> ConfigurePythonContainer/configure-python-container.md
    pythonContainerTitle = "Configure Linux Python apps",
    pythonContainerDescription = "Learn how to configure the Python container in which web apps are run, using both the Azure portal and the Azure CLI.",
    // these are the strings for -> CreateSpeechService/create-speech-service.md
    speechServiceTitle = "Deploy an Azure AI Speech service",
    speechServiceDescription = "In this Azure AI Speech CLI quickstart, you interact with speech to text, text to speech, and speech translation without having to write code.",
    // these are the strings for -> DeployPremiumSSDV2/deploy-premium-ssd-v2.md
    ssdv2Title = "Deploy a Premium SSD v2 managed disk",
    ssdv2Description = "Learn how to deploy a Premium SSD v2 and about its regional availability.",
    // these are the strings for -> PostgresRagLlmDemo/README.md
    postgresRagTitle = "Deploy a Postgres vector database",
    postgresRagDescription = "Set up a Postgres vector database and openai resources to run a RAG-LLM model.",
    // these are the strings for -> CreateAOAIDeployment/create-aoai-deployment.md
    aoaDeployTitle = "Deploy an Azure OpenAI Service",
    aoaDeployDescription = "Learn how to use the Azure CLI to create an Azure OpenAI resource and manage deployments with the Azure OpenAI Service.",
    // these are the strings for -> AksKaito/README.md
    aksKaitoTitle = "Deploy an AI model on AKS with the AI toolchain operator",
    aksKaitoDescription = "Learn how to enable the AI toolchain operator add-on on Azure Kubernetes Service (AKS) to simplify OSS AI model management and deployment",
    aksKaitoNextStepOne = "Check out the KAITO GitHub repository",
    // these are the strings for -> azure-docs/articles/confidential-computing/confidential-enclave-nodes-aks-get-started.md
    enclaveNodesTitle = "Quickstart: Deploy an AKS cluster with confidential computing Intel SGX agent nodes by using the Azure CLI",
    enclaveNodesDescription = "Learn how to create an Azure Kubernetes Service (AKS) cluster with enclave confidential containers a Hello World app by using the Azure CLI.",
    enclaveNodesNextStepOne = "Samples to run Python, Node, and other applications through confidential containers",
    enclaveNodesNextStepTwo = "Enclave-aware Azure container samples in GitHub",
    // these are the strings for -> azure-management-docs/articles/azure-linux/quickstart-azure-cli.md
    quickAzureCliTitle = "Quickstart: Deploy an Azure Linux Container Host for AKS cluster by using the Azure CLI",
    quickAzureCliDescription = "Learn how to quickly create an Azure Linux Container Host for AKS cluster using the Azure CLI.",
    quickAzureCliNextStepOne = "Azure Linux Container Host tutorial",
    // these are the strings for -> azure-docs/articles/virtual-machine-scale-sets/tutorial-use-custom-image-cli.md
    customImageCliTitle = "Tutorial - Use a custom VM image in a scale set with Azure CLI",
    customImageCliDescription = "Learn how to use the Azure CLI to create a custom VM image that you can use to deploy a Virtual Machine Scale Set",
    customImageNextStepOne = "Deploy applications to your scale sets",
    // these are the strings for -> azure-docs/articles/virtual-network/create-virtual-machine-accelerated-networking.md
    vmAccNetworkTitle = "Create an Azure Virtual Machine with Accelerated Networking",
    vmAccNetworkDescription = "Use Azure portal, Azure CLI, or PowerShell to create Linux or Windows virtual machines with Accelerated Networking enabled for improved network performance.",
    vmAccNetworkNextStepOne = "How Accelerated Networking works in Linux and FreeBSD VMs",
    // These are the strings for -> azure-aks-docs/articles/aks/workload-identity-migrate-from-pod-identity.md
    podIdentityTitle = "Migrate your Azure Kubernetes Service (AKS) pod to use workload identity",
    podIdentityDescription = "In this Azure Kubernetes Service (AKS) article, you learn how to configure your Azure Kubernetes Service pod to authenticate with workload identity.",
    podIdentityNextStepOne = "Use Microsoft Entra Workload ID with Azure Kubernetes Service (AKS)",
    // these are the strings for -> DeployTensorflowOnAKS/deploy-tensorflow-on-aks.md
    tensorFlowTitle = "Setup: Deploy a Tensorflow Cluster on Azure Kubernetes Service (AKS)",
    tensorFlowDescription = "Learn how to deploy a Tensorflow cluster on Azure Kubernetes Service (AKS) using Azure CLI.",
    // these are strings for -> FixFstabIssuesRepairVM/fix-fstab-issues-repair-vm.md
    fstabTitle = "Troubleshoot Linux VM boot issues due to fstab errors",
    fstabDescription = "Explains why Linux VM cannot start and how to solve the problem.",
    createSupportRequestTitle = "Create a Support Request for your VM",
    // these are strings for -> KernelBootIssuesRepairVM/kernel-related-boot-issues-repairvm.md
    kernelPanicTitle = "Recover Azure Linux VM from kernel panic due to missing initramfs",
    kernelPanicDescription = "Provides solutions to an issue in which a Linux virtual machine (VM) can't boot after applying kernel changes",
    // these are strings for -> TroubleshootVMGrubError/troubleshoot-vm-grub-error-repairvm.md
    grubRescueTitle = "Linux VM boots to GRUB rescue",
    grubRescueDescription = "Provides troubleshooting guidance for GRUB rescue issues with Linux virtual machines.",
    // these are strings for -> azure-docs/articles/batch/quick-create-cli.md
    batchQuickstartTitle = "Quickstart: Use the Azure CLI to create a Batch account and run a job",
    batchQuickstartDescription = "Follow this quickstart to use the Azure CLI to create a Batch account, a pool of compute nodes, and a job that runs basic tasks on the pool.",
    batchNextStepOne = "Tutorial: Run a parallel workload with Azure Batch",
    // these are strings for -> azure-compute-docs/articles/virtual-machines/linux/tutorial-manage-vm.md
    manageLinuxVmTitle = "Tutorial - Create and manage Linux VMs with the Azure CLI",
    manageLinuxVmDescription = "In this tutorial, you learn how to use the Azure CLI to create and manage Linux VMs in Azure",
    manageLinuxVmNextStepOne = "Create and Manage VM Disks",
    // these are strings for -> azure-compute-docs/articles/virtual-machine-scale-sets/tutorial-autoscale-cli.md
    autoscaleVmssTitle = "Tutorial - Autoscale a scale set with the Azure CLI",
    autoscaleVmssDescription = "Learn how to use the Azure CLI to automatically scale a Virtual Machine Scale Set as CPU demands increases and decreases",
    autoscaleVmssNextStepOne = "Learn about scale set instance protection",
    // these are the strings for -> azure-compute-docs/articles/virtual-machine-scale-sets/tutorial-modify-scale-sets-cli.md
    modifyVmssTitle = "Modify an Azure Virtual Machine Scale Set using Azure CLI",
    modifyVmssDescription = "Learn how to modify and update an Azure Virtual Machine Scale Set using Azure CLI",
    modifyVmssNextStepOne = "Use data disks with scale sets",
    // these are strings for -> azure-compute-docs/articles/virtual-machines/disks-enable-performance.md
    diskPerfTitle = "Preview - Increase performance of Premium SSDs and Standard SSD/HDDs",
    diskPerfDescription = "Increase the performance of Azure Premium SSDs and Standard SSD/HDDs using performance plus.",
    diskPerfNextStepOne = "Create an incremental snapshot for managed disks",
    diskPerfNextStepTwo = "Expand virtual hard disks on a Linux VM",
    diskPerfNextStepThree = "How to expand virtual hard disks attached to a Windows virtual machine",
    // these are strings for -> azure-compute-docs/articles/container-instances/container-instances-vnet.md
    aciVnetTitle = "Deploy container group to Azure virtual network",
    aciVnetDescription = "Learn how to deploy a container group to a new or existing Azure virtual network via the Azure CLI.",
    aciVnetNextStepOne = "Create an Azure container group with virtual network",
    aciVnetNextStepTwo = " Deploy to Azure Container Instances from Azure Container Registry using a managed identity",
    // these are strings for -> azure-compute-docs/articles/virtual-machines/linux/multiple-nics.md
    multiNicVmTitle = "Create a Linux VM in Azure with multiple NICs",
    multiNicVmDescription = "Learn how to create a Linux VM with multiple NICs attached to it using the Azure CLI or Resource Manager templates.",
    multiNicVmNextStepOne = "Review Linux VM Sizes",
    multiNicVmNextStepTwo = "Manage virtual machine access using just in time",
    // these are strings for -> azure-compute-docs/articles/virtual-machines/linux/quick-create-terraform/quick-create-terraform.md
    terraformVmTitle = "Quickstart: Use Terraform to create a Linux VM",
    terraformVmDescription = "In this quickstart, you learn how to use Terraform to create a Linux virtual machine.",
    terraformVmNextStepOne = "Troubleshoot common problems when using Terraform on Azure",
    terraformVmNextStepTwo = "Azure Linux Virtual Machine Tutorials",
    // these are strings for -> upstream/FlatcarOnAzure/flatcar-on-azure.md
    flatcarTitle = "Running Flatcar Container Linux on Microsoft Azure",
    flatcarDescription = "Deploy Flatcar Container Linux in Microsoft Azure by creating resource groups and using official marketplace images.",
    // these are strings for -> azure-management-docs/articles/azure-linux/tutorial-azure-linux-migration.md
    azLinuxMigrateTitle = "Azure Linux Container Host for AKS tutorial - Migrating to Azure Linux",
    azLinuxMigrateDescription = "In this Azure Linux Container Host for AKS tutorial, you learn how to migrate your nodes to Azure Linux nodes.",
    azLinuxMigrateNextStepOne = "Enable telemetry and monitoring",
    // these are strings for -> azure-management-docs/articles/azure-linux/tutorial-azure-linux-create-cluster.md
    azLinuxCreateClusterTitle = "Azure Linux Container Host for AKS tutorial - Create a cluster",
    azLinuxCreateClusterDescription = "In this Azure Linux Container Host for AKS tutorial, you will learn how to create an AKS cluster with Azure Linux.",
    azLinuxCreateClusterNextStepOne = "Add an Azure Linux node pool",
    // these are the strings for -> azure-management-docs/articles/azure-linux/tutorial-azure-linux-add-nodepool.md
    azLinuxAddNodepoolTitle = "Azure Linux Container Host for AKS tutorial - Add an Azure Linux node pool to your existing AKS cluster",
    azLinuxAddNodepoolDescription = "In this Azure Linux Container Host for AKS tutorial, you learn how to add an Azure Linux node pool to your existing cluster.",
    azLinuxAddNodepoolNextStepOne = "Migrating to Azure Linux",
    // these are the strings for -> azure-management-docs/articles/azure-linux/tutorial-azure-linux-upgrade.md
    azLinuxUpgradeTitle = "Azure Linux Container Host for AKS tutorial - Upgrade Azure Linux Container Host nodes",
    azLinuxUpgradeDescription = "In this Azure Linux Container Host for AKS tutorial, you learn how to upgrade Azure Linux Container Host nodes.",
    azLinuxUpgradeNextStepOne = "Azure Linux Container Host Overview",
    // these are the strings for -> azure-management-docs/articles/azure-linux/tutorial-azure-linux-telemetry-monitor.md
    azLinuxTelemetryTitle = "Azure Linux Container Host for AKS tutorial - Enable telemetry and monitoring for the Azure Linux Container Host",
    azLinuxTelemetryDescription = "In this Azure Linux Container Host for AKS tutorial, you'll learn how to enable telemetry and monitoring for the Azure Linux Container Host.",
    azLinuxTelemetryNextStepOne = "Upgrade Azure Linux Nodes",
    // these are strings for -> azure-stack-docs/azure-stack/user/azure-stack-quick-create-vm-linux-cli.md
    azStackVmTitle = "Create Linux VM with Azure CLI in Azure Stack Hub",
    azStackVmDescription = "Create a Linux virtual machine by using the Azure CLI in Azure Stack Hub.",
    azStackVmNextStepOne = "Considerations for virtual machines in Azure Stack Hub",
    // these are strings for -> azure-aks-docs/articles/aks/azure-cni-powered-by-cilium.md
    cniCiliumTitle = "Configure Azure CNI Powered by Cilium in Azure Kubernetes Service (AKS)",
    cniCiliumDescription = "Learn how to create an Azure Kubernetes Service (AKS) cluster with Azure CNI Powered by Cilium.",
    cniCiliumNextStepOne = "Upgrade Azure CNI IPAM modes and Dataplane Technology.",
    cniCiliumNextStepTwo = "Use a static IP address with the Azure Kubernetes Service (AKS) load balancer",
    cniCiliumNextStepThree = "Use an internal load balancer with Azure Container Service (AKS)",
    cniCiliumNextStepFour = "Create a basic ingress controller with external network connectivity",
    // these are strings for -> azure-compute-docs/articles/virtual-machines/linux/tutorial-automate-vm-deployment.md
    cloudInitVmTitle = "Tutorial - Customize a Linux VM with cloud-init in Azure",
    cloudInitVmDescription = "In this tutorial, you learn how to use cloud-init and Key Vault to customize Linux VMs the first time they boot in Azure",
    cloudInitVmNextStepOne = "Create custom VM images",
    // these are strings for -> azure-compute-docs/articles/virtual-machines/linux/tutorial-lamp-stack.md
    lampWpVmTitle = "Tutorial - Deploy LAMP and WordPress on a VM",
    lampWpVmDescription = "In this tutorial, you learn how to install the LAMP stack, and WordPress, on a Linux virtual machine in Azure.",
    lampWpVmNextStepOne = "Secure web server with TLS",
    // these are strings for -> azure-aks-docs/articles/aks/node-image-upgrade.md
    aksNodeImageUpgradeTitle = "Upgrade Azure Kubernetes Service (AKS) node images",
    aksNodeImageUpgradeDescription = "Learn how to upgrade the images on AKS cluster nodes and node pools.",
    aksNodeImageUpgradeNextStepOne = "For information about the latest node images, see the AKS release notes",
    aksNodeImageUpgradeNextStepTwo = "Learn how to upgrade the Kubernetes version with Upgrade an AKS cluster",
    aksNodeImageUpgradeNextStepThree = "Automatically apply cluster and node pool upgrades with GitHub Actions",
    aksNodeImageUpgradeNextStepFour = "Learn more about multiple node pools with Create multiple node pools",
    aksNodeImageUpgradeNextStepFive = "Learn about upgrading best practices with AKS patch and upgrade guidance",
    aksNodePoolNameTitle = "AKS Node Pool Name",
    // these are strings for -> azure-compute-docs/articles/virtual-machines/linux/tutorial-elasticsearch.md
    elasticSearchVmTitle = "Deploy ElasticSearch on a development virtual machine in Azure",
    elasticSearchVmDescription = "Install the Elastic Stack (ELK) onto a development Linux VM in Azure",
    elasticSearchVmNextStepOne = "Create a Linux VM with the Azure CLI",
    // these are strings for -> azure-aks-docs/articles/aks/learn/quick-windows-container-deploy-cli.md
    aksWindowsContainerTitle = "Deploy a Windows Server container on an Azure Kubernetes Service (AKS) cluster using Azure CLI",
    aksWindowsContainerDescription = "Learn how to quickly deploy a Kubernetes cluster and deploy an application in a Windows Server container in Azure Kubernetes Service (AKS) using Azure CLI.",
    aksWindowsContainerNextStepOne = "AKS solution guidance",
    aksWindowsContainerNextStepTwo = "AKS tutorial",
    // these are strings for -> azure-aks-docs/articles/aks/spot-node-pool.md
    aksSpotNodepoolTitle = "Add an Azure Spot node pool to an Azure Kubernetes Service (AKS) cluster",
    aksSpotNodepoolDescription = "Learn how to add an Azure Spot node pool to an Azure Kubernetes Service (AKS) cluster.",
    aksSpotNodepoolNextStepOne = "Best practices for advanced scheduler features in AKS",
    // these are strings for -> azure-aks-docs/articles/aks/auto-upgrade-cluster.md
    aksAutoUpgradeClusterTitle = "Automatically upgrade an Azure Kubernetes Service (AKS) cluster",
    aksAutoUpgradeClusterDescription = "Learn how to automatically upgrade an Azure Kubernetes Service (AKS) cluster to get the latest features and security updates.",
    aksAutoUpgradeClusterNextStepOne = "AKS Patch and Upgrade Guidance",
    // these are strings for -> azure-aks-docs/articles/aks/auto-upgrade-node-os-image.md
    aksAutoUpgradeNodeOsTitle = "autoupgrade Node OS Images",
    aksAutoUpgradeNodeOsDescription = "Learn how to automatically upgrade an Azure Kubernetes Service (AKS) cluster to get the latest features and security updates.",
    aksAutoUpgradeNodeOsNextStepOne = "AKS Patch and Upgrade Guidance",
    // these are strings for -> azure-aks-docs/articles/aks/cost-analysis.md
    aksCostAnalysisTitle = "Azure Kubernetes Service (AKS) cost analysis",
    aksCostAnalysisDescription = "Learn how to use cost analysis to surface granular cost allocation data for your Azure Kubernetes Service (AKS) cluster.",
    aksCostAnalysisNextStepOne = "Understand Azure Kubernetes Service (AKS) usage and costs",
    // these are strings for -> azure-aks-docs/articles/aks/istio-deploy-addon.md
    aksIstioAddonTitle = "Deploy Istio-based service mesh add-on for Azure Kubernetes Service",
    aksIstioAddonDescription = "Deploy Istio-based service mesh add-on for Azure Kubernetes Service",
    aksIstioAddonNextStepOne = "Deploy external or internal ingresses for Istio service mesh add-on",
    aksIstioAddonNextStepTwo = "Scale istiod and ingress gateway HPA",
    aksIstioAddonNextStepThree = "Collect metrics for Istio service mesh add-on workloads in Azure Managed Prometheus",
    workloadsDeploymentFailedString = "Deployment failed",
    workloadsManageResourcesString = "To manage your application, we are currently organizing your resources by function.",
    workloadsDeploymentSuccessfulString = "Deployed successfully",
    workloadsInProgressString = "In progress, view terminal for details",
    // new Executable docs batch 6/26/25 strings
    istioServiceMeshTitle = "Istio Service Mesh Azure Kubernetes Service Add-On Performance and Scaling",
    nodeNotReadyCseErrorsTitle = "Troubleshooting - Node Not Ready because of custom script extension (CSE) errors",
    availabilitySetVmNameParam = "Availability Set VM Name",
    nodeNotReadyHealthyStateTitle = "Troubleshooting - Node Not Ready Status After Node is in a Healthy State",
    tcpTimeoutKubeletTitle = "Troubleshooting - TCP 10250 I/O Timeout Errors when Connecting to a Node's Kubelet for Log Retrieval",
    podNameParam = "Pod Name",
    viewKubeletLogsTitle = "View Kubelet Logs in Azure Kubernetes Service (AKS)",
    sshIntoAksNodesNextStep = "SSH into AKS Cluster Nodes",
    nodeNameParam = "Node Name",
    deleteAksClusterTitle = "Delete an Azure Kubernetes Service (AKS) cluster",
    stopAksClusterNextStep = "Stop an AKS Cluster",
    upgradeAksClusterNextStep = "Upgrade an AKS Cluster",
    migrateToAksTitle = "Migrate to Azure Kubernetes Service (AKS)",
    enhancingConcurrencyETagsTitle = "Enhancing Concurrency Control with Entity Tags (eTags) in Azure Kubernetes Service",
    accessPrivateAksClusterTitle = "Access a Private Azure Kubernetes Service (AKS) Cluster using the Command Invoke or Run Command Feature",
    troubleshootDnsLookupFailTitle = "Troubleshooting - Troubleshoot the K8SAPIServerDNSLookupFailVMExtensionError Error Code (52)",
    privateAksCustomDnsNextStep = "Private Azure Kubernetes Service with Custom DNS server",
    resizeAksClustersTitle = "Resize Azure Kubernetes Service (AKS) Clusters",
    numberOfNodesParam = "Number of Nodes",
    nodePoolNameParam = "Node Pool Name",
    aksPreviewApiLifecycleTitle = "AKS Preview API Life Cycle",
    aksPreviewCliExtensionNextStep = "AKS Preview CLI Extension",
    newerVersionSdkNextStep = "Newer Version of the SDK",
    useLabelsInAksTitle = "Use Labels in an Azure Kubernetes Service (AKS) Cluster",
    aksCostAnalysisIssuesTitle = "Azure Kubernetes Service Cost Analysis Add-on Issues",
    troubleshootHealthProbeModeTitle = "Troubleshooting - Troubleshoot the Health Probe Mode for AKS Cluster Service Load Balancer",
    troubleshootCniDownloadFailuresTitle = "Troubleshooting - Troubleshoot Container Network Interface Download Failures",
    tcpTimeoutsKubectlApiTitle = "Troubleshooting - TCP Time-outs when Kubectl or Other 3rd-party Tools connect to API",
    enableHostBasedEncryptionTitle = "Enable Host-Based Encryption on Azure Kubernetes Service (AKS)",
    aksPricingTiersTitle = "Azure Kubernetes Service (AKS) Free, Standard, and Premium pricing tiers for cluster management",
    useKubernetesEventsTitle = "Troubleshooting - Use Kubernetes Events for Troubleshooting",
    troubleshootClusterUpgradingTitle = "Troubleshooting - Troubleshoot Cluster Upgrading and Scaling Errors",
    troubleshootForbiddenErrorTitle = "Troubleshooting - Troubleshoot 'Forbidden' Error when trying to access AKS Cluster Resources",
    troubleshootApiServerConnectionTitle = "Troubleshooting - Troubleshoot Cluster Connection Issues with the API Server",
    aadstsBadRequestErrorTitle = "Troubleshooting - AADSTS7000222 - BadRequest or InvalidClientSecret error",
    aksResourceGroupNameParam = "AKS Resource Group Name",
    clusterNameParam = "Cluster Name",
    istioMeshConfigTitle = "Configure Istio-based Service Mesh Add-on for Azure Kubernetes Service",
    istioMeshConfigDescription = "Configure Istio-based service mesh add-on for Azure Kubernetes Service",
    accessPrivateAksClusterDescription = "Learn how to access a private Azure Kubernetes Service (AKS) cluster using the Azure CLI command invoke feature or the Azure portal Run command feature.",
    troubleshootDnsLookupFailDescription = "Learn how to troubleshoot the K8SAPIServerDNSLookupFailVMExtensionError error (52) when you try to start or create and deploy an Azure Kubernetes Service (AKS) cluster.",
    resizeAksClustersDescription = "In this article, you learn about the importance of right-sizing your AKS clusters and how you can right-size them to optimize costs and performance.",
    aksPreviewApiLifecycleDescription = "Learn about the AKS preview API life cycle.",
    terraformProviderClientGoTitle = "client.go in Terraform Provider",
    useLabelsInAksDescription = "Learn how to use labels in an Azure Kubernetes Service (AKS) cluster.",
    aksCostAnalysisIssuesDescription = "Learn how to resolve issues that occur when you try to enable the Azure Kubernetes Service (AKS) Cost Analysis add-on.",
    troubleshootHealthProbeModeDescription = "Diagnoses and fixes common issues with the health probe mode feature.",
    troubleshootCniDownloadFailuresDescription = "Learn how to resolve Container Network Interface download failures when you try to create and deploy an Azure Kubernetes Service (AKS) cluster.",
    tcpTimeoutsKubectlApiDescription = "Troubleshoot TCP time-outs that occur when kubectl or other third-party tools connect to the API server in Azure Kubernetes Service (AKS).",
    enableHostBasedEncryptionDescription = "Learn how to configure a host-based encryption in an Azure Kubernetes Service (AKS) cluster.",
    natGatewayAksTitle = "Create a Managed or User-Assigned NAT Gateway for your Azure Kubernetes Service (AKS) cluster",
    natGatewayAksDescription = "Learn how to create an AKS cluster with managed NAT integration and user-assigned NAT gateway.",
    aksPricingTiersDescription = "Learn about the Azure Kubernetes Service (AKS) Free, Standard, and Premium pricing plans and what features, deployment patterns, and recommendations to consider between each plan.",
    useKubernetesEventsDescription = "Learn about Kubernetes events, which provide details on pods, nodes, and other Kubernetes objects.",
    troubleshootClusterUpgradingDescription = "Troubleshoot errors that occur when you try to upgrade or scale an Azure Kubernetes Service (AKS) cluster.",
    troubleshootForbiddenErrorDescription = "Troubleshoot 'Error from server (Forbidden)' RBAC-related errors that occur when you try to view Kubernetes resources in an AKS cluster.",
    troubleshootApiServerConnectionDescription = "Troubleshoot issues that occur when you attempt to connect to the API server of an Azure Kubernetes Service (AKS) cluster.",
    clientIpCannotAccessApiTitle = "Client IP Address cannot Access the API Server",
    clientIpCannotAccessApiDescription = "Troubleshoot issues caused when the client IP address can't access the API server on an Azure Kubernetes Service (AKS) cluster.",
    aadstsBadRequestErrorDescription = "Learn how to troubleshoot the BadRequest or InvalidClientSecret error when you try to create or upgrade an Azure Kubernetes Service (AKS) cluster.",
    clusterAutoscalerFailsToScaleTitle = "Cluster Autoscaler Fails to Scale with 'Cannot Scale Cluster Autoscaler Enabled Node Pool' Error",
    clusterAutoscalerFailsToScaleDescription = "Learn how to troubleshoot the 'Cannot Scale Cluster Autoscaler Enabled Node Pool' error when your autoscaler isn't scaling up or down.",
    istioServiceMeshScalingDescription = "Istio Service Mesh Azure Kubernetes Service add-on performance and scaling.",
    nodeNotReadyCseErrorsDescription = "Troubleshoot scenarios in which custom script extension (CSE) errors cause Node Not Ready states in an Azure Kubernetes Service (AKS) cluster node pool.",
    nodeNotReadyHealthyStateDescription = "Troubleshoot scenarios in which an Azure Kubernetes Service (AKS) cluster node goes to a Not Ready status after is in a healthy state.",
    tcpTimeoutKubeletDescription = "Learn how to troubleshoot TCP 10250 I/O timeout errors that occur when retrieving kubectl logs from a pod in an Azure Kubernetes Service (AKS) cluster.",
    viewKubeletLogsDescription = "Learn how to view troubleshooting information in the kubelet logs from Azure Kubernetes Service (AKS) nodes",
    deleteAksClusterDescription = "Learn about deleting a cluster in Azure Kubernetes Service (AKS).",
    controlClusterAccessConditionalAccessTitle = "Control Cluster Access using Conditional Access with AKS-managed Microsoft Entra integration",
    controlClusterAccessConditionalAccessDescription = "Learn how to access clusters using Conditional Access when integrating Microsoft Entra ID in your Azure Kubernetes Service (AKS) clusters.",
    azureCniPodSubnetTitle = "Concepts - Azure CNI Pod Subnet Networking in AKS",
    azureCniPodSubnetDescription = "Learn about Azure CNI Pod Subnet, dynamic IP allocation mode, and static block allocation mode in Azure Kubernetes Service (AKS).",
    migrateToAksDescription = "This article shows you how to migrate to Azure Kubernetes Service (AKS).",
    enhancingConcurrencyETagsDescription = "Learn how to use eTags (Entity Tags) to enable concurrency control and avoid racing conditions or overwriting scenarios.",
}