name: build-test-release

on:
  push:
    branches:
      - main
      - vmarcella/port-to-go

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build all targets.
      run: |
        make build-all
    - name: Run unit tests across all targets.
      run: |
        make test-all
