name: build-test-release

on:
  push:
    branches:
      - main
      - vmarcella/port-to-go

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build all targets.
      run: |
        make build-all
    - name: Run unit tests across all targets.
      run: |
        make test-all
    - name: Release Innovation Engine
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        prelease: true
        files: ./bin
