name: scenario-testing
on:
  schedule:
    - cron: "0 */2 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  test-ocd-scenarios:
    runs-on: ubuntu-latest
    # This is needed in order to obtain OIDC tokens to sign this pipeline into 
    # the testing subscription for any branch in this repository.
    environment: Production
    steps:
      - uses: actions/checkout@v2
      - name: Build all targets.
        run: |
          make build-all
          make test-all
      - name: Sign into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
      - name: Run all one click deployment scenarios.
        uses: azure/CLI@v1
        if: github.event_name != 'pull_request'
        with:
          inlineScript: |
            apk add --no-cache make
            make test-scenarios SUBSCRIPTION=${{ secrets.AZURE_SUBSCRIPTION }}
      - name: Display ie.log file
        if: github.event_name != 'pull_request'
        run: |
          cat ie.log
